### ISSUE TITLE
Session Crashed 

### ISSUE THREAD

**Issue by Mohima17** [miniufo/xvortices#1]
Hello, Thank you for making this repository available. 

I am using google colab. I ran the code onto my dataset. But the session crashes everytime. 

sla, lons, lats, etas = load_cylind(dset['sla'],
                                     olon=olon, olat=olat, # center positions of eddy
                                     azimNum=72,           # 72 points azimuthally
                                    radiNum=31,           # 31 points radially
                                      radMax=2,             # max radius of 4 degree (444km)
                                      lonname='longitude',  # lat/lon names in gridded dataset
                                      latname='latitude')

I have identified eddies from the https://py-eddy-tracker.readthedocs.io/en/latest/. 

What will be your recommendations in this regard?

**Comment by Mohima17** [comment]
In the eddyExample code, you have transformed eddy from geographic coordinate to cylindrical coordinate (only one eddy). Can I transform all detected eddies to a single coordinate? 


Also, in the journal papers, normalised eddy coordinate system is created by dividing the lat/lon by the eddy radius. But in your code, you did not do that. Is it not necessary to form a eddy composite?

**Comment by Mohima17** [comment]
Can we have a conversation? My email is -- mimi.mohimaa@gmail.com

**Comment by miniufo** [comment]
Hi @Mohima17, thank you for your interests.  Can you post your screenshot or the error reports?  I've no idea about the crash of your session.

> In the eddyExample code, you have transformed eddy from geographic coordinate to cylindrical coordinate (only one eddy). Can I transform all detected eddies to a single coordinate?

Yes, with python it is much easy to do this as:
```python
transformed = [transform(eddy) for eddy in eddies]
```

You have to implement the `transform()` function for yourself.

>Also, in the journal papers, normalised eddy coordinate system is created by dividing the lat/lon by the eddy radius. But in your code, you did not do that. Is it not necessary to form a eddy composite?

This is an interesting thing that I didn't think about.  Now we can get the radius, and we only need to normalize it in unit of Reddy.  For a single time step, it is not hard because you can just do `eddy['radi'] = eddy['radi'] / Reddy`.  The thing is that Reddy change with time.  So that after this normalization, the radial coordinates do not align for different times, and hence hamper the composite.  Do you have any suggestion on how to do this?

**Comment by Mohima17** [comment]
Thank you for your reply.

**Comment by Mohima17** [comment]
I found this code for eddy composite:



grid=numpy.zeros([200,160]) ###establish an empty matrix to store the variables to be analyzed
num=numpy.zeros([200,160]) ###establish an empty matrix for counting

for data in datas: ###Iterate over the dataset
        e_lon=data['eddy_core']['lon']
        e_lat=data['eddy_core']['lat'] ###eddy location
        f_lon=data['Argo']['lon']
        f_lat=data['Argo']['lat']  ###float location
        angle=angl(e_lat,e_lon,f_lat,f_lon)  ###Computing the position of the float to the eddy centre
        R=cal_dis(e_lat,e_lon,f_lat,f_lon)/data['eddy_radius']  ###Computing the the normalised distance of the float to the eddy centre (0<=R<=2)
        depth=data['thermocline anomaly']

        ###Coordinate Translation###
        r=k/0.02
        orr=1  ### 1 for the circular normalisation; 1.6 for the ellipse normalisation
        rr=(orr**2)/(1+(orr**2-1)*(np.sin(angle/180*np.pi)**2))
        rr=rr**0.5
        r=r*rr
        dx=math.ceil(r*math.cos(angle/180*np.pi))
        dy=math.ceil(r*math.sin(angle/180*np.pi))
        ss2=(opss-1)/2

        grid[math.ceil(100+dy)][math.ceil(ss2+dx)]+=depth
        num[math.ceil(100+dy)][math.ceil(ss2+dx)]+=1

###Averaged for all data###
for i in range(200):
        for j in range(160):  
            if grid[i][j]>0:
                grid[i][j]=grid[i][j]/num[i][j]

**Comment by Mohima17** [comment]
Could you please explain azimNum and radiNum a bit explicitly? and how to correctly choose these values?

**Comment by miniufo** [comment]
You can find the doc string at [here](https://github.com/miniufo/xvortices/blob/bcfded54e1f9fa31e75aad6200aa652f96e363fe/xvortices/core.py#L33) for `radiNum` and `azimNum`, which are the numbers of grid points along radial and azimuthal directions defined by users themselves.

**Comment by Mohima17** [comment]
Thank you for your reply
