### ISSUE TITLE
AttributeError: 'TC' object has no attribute 'get_as_xarray'

### ISSUE THREAD

**Issue by Matwayi** [miniufo/xvortices#3]
![dd62323bfe447dc2c1bb7eaff1bcda1](https://user-images.githubusercontent.com/40701478/207762142-49649d48-aa0e-4076-b461-a45bbc62f9cf.png)

**Comment by miniufo** [comment]
Sorry about this.  I forgot to updated `besttracks`.  Now it is updated and you can download [`core.py`](https://github.com/miniufo/besttracks/blob/master/besttracks/core.py) to replace your `besttracks` source codes and rerun this notebook.

**Comment by Matwayi** [comment]
> Sorry about this. I forgot to updated `besttracks`. Now it is updated and you can download [`core.py`](https://github.com/miniufo/besttracks/blob/master/besttracks/core.py) to replace your `besttracks` source codes and rerun this notebook.

Thank you for updating it, working now.
